"""Static goal tile and bonus card catalogues, loaded from data/*.json.

The JSON is generated by `scripts/build_catalogues.py` and committed, so the
app has no network dependency at runtime. See that script for provenance.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from wingspan.db import ROOT
from wingspan.model import Expansion

GOAL_TILES_PATH = ROOT / "data" / "goal_tiles.json"
BONUS_CARDS_PATH = ROOT / "data" / "bonus_cards.json"

#: Used when a game records a goal or card that is not in the catalogue.
CUSTOM_GOAL_ID = "g_custom"
CUSTOM_BONUS_ID = "b_custom"


@dataclass(frozen=True)
class BonusCard:
    id: str
    name: str
    expansion: Expansion
    condition: str = ""
    description: str = ""
    vp_text: str = ""
    scoring_type: str = "tiered"

    @property
    def summary(self) -> str:
        return self.condition or self.description or self.name


@dataclass(frozen=True)
class GoalTile:
    """One end-of-round goal tile.

    The tile says *what* is being counted. How that converts to points is a
    property of the goal board -- the round and the number of players -- so the
    arithmetic lives in `wingspan.goals`, which this type defers to.
    """

    id: str
    name: str
    expansion: Expansion
    green_description: str = ""
    blue_description: str = ""
    family: str = "other"
    scoring_type: str = "placement"

    def description_for(self, side: object) -> str:
        from wingspan.model import GoalSide

        if side is GoalSide.BLUE and self.blue_description:
            return self.blue_description
        return self.green_description or self.name

    def calculate_score(
        self,
        placements,
        player_count: int,
        *,
        round_no: int,
        side=None,
        counts=None,
    ) -> dict[str, int]:
        """Points per player for this tile in one round. Pure.

        `placements` maps player id to 1/2/3 or None on the green side; on the
        blue side pass `counts` instead. Delegates to the scoring strategy
        named by `scoring_type`, so a future expansion tile that scores some
        other way only needs a new strategy, not new call sites.
        """
        from wingspan import goals as goals_mod

        return goals_mod.score_round(
            round_no=round_no,
            side=side,
            placements=placements,
            counts=counts,
            player_count=player_count,
            scoring_type=self.scoring_type,
        )


def _read(path: Path) -> list[dict]:
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload.get("entries", []) if isinstance(payload, dict) else payload


def _expansion(raw: str) -> Expansion:
    try:
        return Expansion(raw)
    except ValueError:
        return Expansion.BASE


@lru_cache(maxsize=1)
def goal_tiles() -> tuple[GoalTile, ...]:
    tiles = tuple(
        GoalTile(
            id=entry["id"],
            name=entry["name"],
            expansion=_expansion(entry.get("expansion", "")),
            green_description=entry.get("green_description", ""),
            blue_description=entry.get("blue_description", ""),
            family=entry.get("family", "other"),
            scoring_type=entry.get("scoring_type", "placement"),
        )
        for entry in _read(GOAL_TILES_PATH)
    )
    return tiles + (
        GoalTile(
            id=CUSTOM_GOAL_ID,
            name="Other / not listed",
            expansion=Expansion.BASE,
            green_description="A goal that is not in the catalogue",
            family="other",
        ),
    )


@lru_cache(maxsize=1)
def bonus_cards() -> tuple[BonusCard, ...]:
    cards = tuple(
        BonusCard(
            id=entry["id"],
            name=entry["name"],
            expansion=_expansion(entry.get("expansion", "")),
            condition=entry.get("condition", ""),
            description=entry.get("description", ""),
            vp_text=entry.get("vp_text", ""),
            scoring_type=entry.get("scoring_type", "tiered"),
        )
        for entry in _read(BONUS_CARDS_PATH)
    )
    return cards + (
        BonusCard(
            id=CUSTOM_BONUS_ID,
            name="Other / not listed",
            expansion=Expansion.BASE,
            condition="A bonus card that is not in the catalogue",
        ),
    )


@lru_cache(maxsize=1)
def goal_tiles_by_id() -> dict[str, GoalTile]:
    return {t.id: t for t in goal_tiles()}


@lru_cache(maxsize=1)
def bonus_cards_by_id() -> dict[str, BonusCard]:
    return {c.id: c for c in bonus_cards()}


def goal_tile(tile_id: str | None) -> GoalTile | None:
    return goal_tiles_by_id().get(tile_id) if tile_id else None


def bonus_card(card_id: str | None) -> BonusCard | None:
    return bonus_cards_by_id().get(card_id) if card_id else None


def goal_tile_name(tile_id: str | None) -> str:
    tile = goal_tile(tile_id)
    return tile.name if tile else (tile_id or "—")


def bonus_card_name(card_id: str | None) -> str:
    card = bonus_card(card_id)
    return card.name if card else (card_id or "—")


def _filter_by_expansions(items, expansions):
    """Catalogue entries in play. The custom escape hatch is always offered."""
    chosen = set(expansions) | {Expansion.BASE}
    return tuple(
        item
        for item in items
        if item.expansion in chosen or item.id in {CUSTOM_GOAL_ID, CUSTOM_BONUS_ID}
    )


def goal_tiles_for(expansions) -> tuple[GoalTile, ...]:
    return _filter_by_expansions(goal_tiles(), expansions)


def bonus_cards_for(expansions) -> tuple[BonusCard, ...]:
    return _filter_by_expansions(bonus_cards(), expansions)


def reload() -> None:
    """Drop the cached catalogues -- used by tests and after regeneration."""
    for cached in (goal_tiles, bonus_cards, goal_tiles_by_id, bonus_cards_by_id):
        cached.cache_clear()
